# -*- coding: utf-8 -*-
# Generated by Django 1.9.4 on 2016-03-22 22:40
from __future__ import unicode_literals

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Choice',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.CharField(max_length=255, verbose_name='Answer')),
            ],
        ),
        migrations.CreateModel(
            name='CodeGuess',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ip', models.GenericIPAddressField(verbose_name='IP address')),
                ('when_tried', models.DateTimeField(auto_now=True, verbose_name='When')),
                ('guess_code', models.CharField(blank=True, max_length=255, null=True, verbose_name='Invitation code guessed')),
            ],
            options={
                'verbose_name': 'Invitation code guess',
                'verbose_name_plural': 'Invitation code guesses',
            },
        ),
        migrations.CreateModel(
            name='Invitation',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('invite_code', models.CharField(help_text='leave it empty, it will be generated automatically on creation of invitation', max_length=6, verbose_name='invitation code')),
                ('invitation_language', models.CharField(choices=[('af', 'Afrikaans'), ('ar', 'Arabic'), ('ast', 'Asturian'), ('az', 'Azerbaijani'), ('bg', 'Bulgarian'), ('be', 'Belarusian'), ('bn', 'Bengali'), ('br', 'Breton'), ('bs', 'Bosnian'), ('ca', 'Catalan'), ('cs', 'Czech'), ('cy', 'Welsh'), ('da', 'Danish'), ('de', 'German'), ('el', 'Greek'), ('en', 'English'), ('en-au', 'Australian English'), ('en-gb', 'British English'), ('eo', 'Esperanto'), ('es', 'Spanish'), ('es-ar', 'Argentinian Spanish'), ('es-co', 'Colombian Spanish'), ('es-mx', 'Mexican Spanish'), ('es-ni', 'Nicaraguan Spanish'), ('es-ve', 'Venezuelan Spanish'), ('et', 'Estonian'), ('eu', 'Basque'), ('fa', 'Persian'), ('fi', 'Finnish'), ('fr', 'French'), ('fy', 'Frisian'), ('ga', 'Irish'), ('gd', 'Scottish Gaelic'), ('gl', 'Galician'), ('he', 'Hebrew'), ('hi', 'Hindi'), ('hr', 'Croatian'), ('hu', 'Hungarian'), ('ia', 'Interlingua'), ('id', 'Indonesian'), ('io', 'Ido'), ('is', 'Icelandic'), ('it', 'Italian'), ('ja', 'Japanese'), ('ka', 'Georgian'), ('kk', 'Kazakh'), ('km', 'Khmer'), ('kn', 'Kannada'), ('ko', 'Korean'), ('lb', 'Luxembourgish'), ('lt', 'Lithuanian'), ('lv', 'Latvian'), ('mk', 'Macedonian'), ('ml', 'Malayalam'), ('mn', 'Mongolian'), ('mr', 'Marathi'), ('my', 'Burmese'), ('nb', 'Norwegian Bokmal'), ('ne', 'Nepali'), ('nl', 'Dutch'), ('nn', 'Norwegian Nynorsk'), ('os', 'Ossetic'), ('pa', 'Punjabi'), ('pl', 'Polish'), ('pt', 'Portuguese'), ('pt-br', 'Brazilian Portuguese'), ('ro', 'Romanian'), ('ru', 'Russian'), ('sk', 'Slovak'), ('sl', 'Slovenian'), ('sq', 'Albanian'), ('sr', 'Serbian'), ('sr-latn', 'Serbian Latin'), ('sv', 'Swedish'), ('sw', 'Swahili'), ('ta', 'Tamil'), ('te', 'Telugu'), ('th', 'Thai'), ('tr', 'Turkish'), ('tt', 'Tatar'), ('udm', 'Udmurt'), ('uk', 'Ukrainian'), ('ur', 'Urdu'), ('vi', 'Vietnamese'), ('zh-hans', 'Simplified Chinese'), ('zh-hant', 'Traditional Chinese')], default='en', max_length=7)),
                ('email_sent', models.BooleanField(default=False, verbose_name='Is email sent?')),
                ('email_sent_at', models.DateTimeField(blank=True, null=True, verbose_name='When sent?')),
            ],
            options={
                'verbose_name': 'Invitation letter',
                'verbose_name_plural': 'Invitation letters',
            },
        ),
        migrations.CreateModel(
            name='InvitationTextTemplate',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='Its used only for administrators to make sense out of template name', max_length=150, verbose_name='Name of template')),
                ('title', models.CharField(max_length=255, verbose_name='Title of invitation')),
                ('body', models.TextField(verbose_name='Body of invitation')),
            ],
            options={
                'verbose_name': 'Invitation text template',
                'verbose_name_plural': 'Invitation text templates',
            },
        ),
        migrations.CreateModel(
            name='Poll',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.TextField(verbose_name='Title')),
                ('description', models.TextField(blank=True, verbose_name='Poll description')),
            ],
        ),
        migrations.CreateModel(
            name='Question',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('question', models.TextField(verbose_name='Question')),
                ('description', models.TextField(blank=True, null=True, verbose_name='Description')),
                ('is_freetext_answer', models.BooleanField(default=False)),
                ('poll', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='questions', to='weddings.Poll')),
            ],
        ),
        migrations.CreateModel(
            name='UserChoice',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('freetext_answer', models.TextField(blank=True, null=True)),
                ('timestamp', models.DateTimeField(default=datetime.datetime.now)),
                ('choice', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='users', to='weddings.Choice')),
                ('invitation', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='poll_answers', to='weddings.Invitation')),
            ],
        ),
        migrations.CreateModel(
            name='WeddingGuest',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=150)),
                ('last_name', models.CharField(blank=True, max_length=150, null=True)),
                ('invited', models.BooleanField(default=False, verbose_name='Is he invited by other guest?')),
                ('email', models.CharField(blank=True, max_length=255, null=True)),
                ('rsvp_answer', models.PositiveSmallIntegerField(choices=[(0, 'Not answered'), (1, 'Will attend'), (2, 'Will not attend'), (3, 'Maybe')], default=0)),
                ('rsvp_change_datetime', models.DateTimeField(blank=True, null=True, verbose_name='RSVP answered date time')),
                ('invitation', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='weddings.Invitation', verbose_name='Invitation letter guest is assigned')),
                ('invited_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='weddings.WeddingGuest', verbose_name='Invited by who?')),
            ],
            options={
                'ordering': ['first_name', 'last_name', '-email'],
                'verbose_name': 'Wedding guest',
                'verbose_name_plural': 'Wedding guests',
            },
        ),
        migrations.AddField(
            model_name='userchoice',
            name='weddingguest',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='poll_answers', to='weddings.WeddingGuest'),
        ),
        migrations.AddField(
            model_name='invitation',
            name='friends',
            field=models.ManyToManyField(blank=True, related_name='_invitation_friends_+', to='weddings.WeddingGuest', verbose_name='Related friends for invitation'),
        ),
        migrations.AddField(
            model_name='invitation',
            name='invitation_text',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='weddings.InvitationTextTemplate', verbose_name='Invitation text template'),
        ),
        migrations.AddField(
            model_name='invitation',
            name='questions',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='weddings.Poll', verbose_name='Questions for invitation'),
        ),
        migrations.AddField(
            model_name='choice',
            name='question',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='choices', to='weddings.Question'),
        ),
        migrations.AlterUniqueTogether(
            name='userchoice',
            unique_together=set([('choice', 'invitation')]),
        ),
    ]
